<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Group extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Group_model');
    } 

    /*
     * Listing of groups
     */
    function index()
    {
        $data['groups'] = $this->Group_model->get_all_groups();
        
        $data['_view'] = 'group/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new group
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('group_name','Group Name','required|max_length[255]');
		$this->form_validation->set_rules('tournament_id','Tournament Id','required|integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'group_name' => $this->input->post('group_name'),
				'tournament_id' => $this->input->post('tournament_id'),
            );
            
            $group_id = $this->Group_model->add_group($params);
            redirect('group/index');
        }
        else
        {  
            $this->load->model('Tournament_model');
			$data['all_tournaments'] = $this->Tournament_model->get_all_tournaments();
            
            $data['_view'] = 'group/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a group
     */
    function edit($group_id)
    {   
        // check if the group exists before trying to edit it
        $data['group'] = $this->Group_model->get_group($group_id);
        
        if(isset($data['group']['group_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('group_name','Group Name','required|max_length[255]');
			$this->form_validation->set_rules('tournament_id','Tournament Id','required|integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'group_name' => $this->input->post('group_name'),
					'tournament_id' => $this->input->post('tournament_id'),
                );

                $this->Group_model->update_group($group_id,$params);            
                redirect('group/index');
            }
            else
            {
                $this->load->model('Tournament_model');
			    $data['all_tournaments'] = $this->Tournament_model->get_all_tournaments();
            
                $data['_view'] = 'group/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The group you are trying to edit does not exist.');
    } 

    /*
     * Deleting group
     */
    function remove($group_id)
    {
        $group = $this->Group_model->get_group($group_id);

        // check if the group exists before trying to delete it
        if(isset($group['group_id']))
        {
            $this->Group_model->delete_group($group_id);
            redirect('group/index');
        }
        else
            show_error('The group you are trying to delete does not exist.');
    }
    
}
