<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Player extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Player_model');
    } 

    /*
     * Listing of players
     */
    function index()
    {
        $data['players'] = $this->Player_model->get_all_players();
        
        $data['_view'] = 'player/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new player
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('player_name','Player Name','required|max_length[150]');
		$this->form_validation->set_rules('player_avatar','Player Avatar','required|max_length[255]');
		$this->form_validation->set_rules('player_email','Player Email','required|max_length[255]|valid_email');
		$this->form_validation->set_rules('company','Company','required');
		$this->form_validation->set_rules('employee_id','Employee Id','required|integer');
		$this->form_validation->set_rules('player_role','Player Role','required');
		$this->form_validation->set_rules('created_at','Created At','required');
		$this->form_validation->set_rules('created_by','Created By','integer');
		$this->form_validation->set_rules('updated_by','Updated By','integer');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'player_name' => $this->input->post('player_name'),
				'player_avatar' => $this->input->post('player_avatar'),
				'player_email' => $this->input->post('player_email'),
				'company' => $this->input->post('company'),
				'employee_id' => $this->input->post('employee_id'),
				'player_role' => $this->input->post('player_role'),
				'created_at' => $this->input->post('created_at'),
				'updated_at' => $this->input->post('updated_at'),
				'created_by' => $this->input->post('created_by'),
				'updated_by' => $this->input->post('updated_by'),
            );
            
            $player_id = $this->Player_model->add_player($params);
            redirect('player/index');
        }
        else
        {            
            $data['_view'] = 'player/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a player
     */
    function edit($player_id)
    {   
        // check if the player exists before trying to edit it
        $data['player'] = $this->Player_model->get_player($player_id);
        
        if(isset($data['player']['player_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('player_name','Player Name','required|max_length[150]');
			$this->form_validation->set_rules('player_avatar','Player Avatar','required|max_length[255]');
			$this->form_validation->set_rules('player_email','Player Email','required|max_length[255]|valid_email');
			$this->form_validation->set_rules('company','Company','required');
			$this->form_validation->set_rules('employee_id','Employee Id','required|integer');
			$this->form_validation->set_rules('player_role','Player Role','required');
			$this->form_validation->set_rules('created_at','Created At','required');
			$this->form_validation->set_rules('created_by','Created By','integer');
			$this->form_validation->set_rules('updated_by','Updated By','integer');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'player_name' => $this->input->post('player_name'),
					'player_avatar' => $this->input->post('player_avatar'),
					'player_email' => $this->input->post('player_email'),
					'company' => $this->input->post('company'),
					'employee_id' => $this->input->post('employee_id'),
					'player_role' => $this->input->post('player_role'),
					'created_at' => $this->input->post('created_at'),
					'updated_at' => $this->input->post('updated_at'),
					'created_by' => $this->input->post('created_by'),
					'updated_by' => $this->input->post('updated_by'),
                );

                $this->Player_model->update_player($player_id,$params);            
                redirect('player/index');
            }
            else
            {
                $data['_view'] = 'player/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The player you are trying to edit does not exist.');
    } 

    /*
     * Deleting player
     */
    function remove($player_id)
    {
        $player = $this->Player_model->get_player($player_id);

        // check if the player exists before trying to delete it
        if(isset($player['player_id']))
        {
            $this->Player_model->delete_player($player_id);
            redirect('player/index');
        }
        else
            show_error('The player you are trying to delete does not exist.');
    }
    
}
