<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Start_match extends CI_Controller
{
	function __construct()
	{
		parent::__construct();

		$user_id = $this->session->userdata('user_id');
		if (!$user_id) {
			$this->logout();
		}
		$this->load->model('Start_match_model');

	}

	function index()
	{
		// echo "<pre>";
		// 	print_r($_POST);
		// 	die;
		$data['params']['is_previous'] = 0;
		if ($this->input->post('matches') != null) {
			
			$data['params'] = $this->getMatchDetails($_POST);
			$data['params']['is_previous'] =  1;

		}
		$data['matches'] = $this->Start_match_model->get_all_match();
		$data['_view'] = 'scoreboard/startmatch_view';
		$this->load->view('layouts/main', $data);
	}

	function select_players()
	{
		$this->form_validation->set_rules('matches', 'Match', 'required');
		$this->form_validation->set_rules('team1', '	Team 1', 'required');
		$this->form_validation->set_rules('team2', '	Team 2', 'required');
		$this->form_validation->set_rules('match_date', 'Match Date', 'required');
		$this->form_validation->set_rules('match_venue', 'Match Venue', 'required');
		$this->form_validation->set_rules('team1_toss', 'Team Toss', 'required');
		$this->form_validation->set_rules('toss_options', 'Toss Options', 'required');
		$this->form_validation->set_rules('overs', 'Overs', 'required');
		if ($this->form_validation->run() == FALSE) {
			$data['matches'] = $this->Start_match_model->get_all_match();
			$data['_view'] = 'scoreboard/startmatch_view';
			$this->load->view('layouts/main', $data);
		}
		else {
			$data['params'] = $this->getMatchDetails($_POST);

			if ($data['params']) {
				$players = $this->Start_match_model->get_all_player($data['params']);
				$data['players'] = $this->arrangePlayers($players);
				$data['_view'] = 'scoreboard/selectplayer_view';
				$this->load->view('layouts/main', $data);
			}
		}
	}

	/**
	 * @param $players
	 * @return array
	 */
	public function arrangePlayers($players)
	{
		$final = [];
		foreach ($players as $player) {
			$final[$player['team']][] = $player;
		}
		return $final;
	}

	public function getMatchDetails($post)
	{
		return array('matches' => $post['matches'], 'team1' => $post['team1'], 'team2' => $post['team2'],
			'teamid_1' => $post['teamid_1'], 'teamid_2' => $post['teamid_2'], 'match_date' => $post['match_date'],
			'match_venue' => $post['match_venue'], 'team1_toss' => $post['team1_toss'], 'toss_options' => $post['toss_options'],
			'overs' => $post['overs']);
	}

	public function logout()
	{
		$this->session->sess_destroy();
		redirect('/');
	}
}


