<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tournament_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tournament by tournament_id
     */
    function get_tournament($tournament_id)
    {
        return $this->db->get_where('tournaments',array('tournament_id'=>$tournament_id))->row_array();
       
    }

    public function get_active_tournament(){
        $this->db->where("is_active","T");
        return $this->db->get('tournaments')->row_array();
    }
        
    /*
     * Get all tournaments
     */
    function get_all_tournaments()
    {
        $this->db->order_by('tournament_id', 'desc');
        return $this->db->get('tournaments')->result_array();
    }
        
    /*
     * function to add new tournament
     */
    function add_tournament($params)
    {
        $this->db->insert('tournaments',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tournament
     */
    function update_tournament($tournament_id,$params)
    {
        $this->db->where('tournament_id',$tournament_id);
        return $this->db->update('tournaments',$params);
    }
    
    /*
     * function to delete tournament
     */
    function delete_tournament($tournament_id)
    {
        return $this->db->delete('tournaments',array('tournament_id'=>$tournament_id));
    }
}
